all:
	ocamlbuild hygears_database.cmo

install: 
	ocamlfind install hygears_database META _build/hygears_database.cm*

remove: 
	ocamlfind remove hygears_database

clean:
	ocamlbuild -clean
	rm -rf *~


